<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "slub_entityfacts"
 *
 * Auto generated by Extension Builder 2018-09-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SLUB Entity Facts',
    'description' => 'Plugin for showing DB Entity Facts',
    'category' => 'plugin',
    'author' => 'Sebastian Semsker',
    'author_email' => 'sebastian.semsker@slub-dresden.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
